### ISSUE TITLE
CollectMetrics call error : Error while parsing

### ISSUE THREAD

**Issue by redsux** [intelsdi-x/snap-plugin-collector-scaleio#3]
Hi,

I've some issue with this plugin, it failed and disabled task as soon as API returns doesn't suit expectation.

My task worked fine during one day then failed ... Last error is : `CollectMetrics call error : Error while parsing data from /api/types/StoragePool/instances: json: cannot unmarshal object into Go value of type []map[string]interface {}`

Metrics collected : `"metrics": {
    "/intel/scaleio/*/capacityInUseInKb": {},
    "/intel/scaleio/*/capacityLimitInKb": {},
    "/intel/scaleio/*/unusedCapacityInKb": {},
    "/intel/scaleio/*/spareCapacityInKb": {},
    "/intel/scaleio/*/failedCapacityInKb": {},
    "/intel/scaleio/*/movingCapacityInKb": {},
    "/intel/scaleio/*/maxCapacityInKb": {},
    "/intel/scaleio/*/numOfDevices": {},
    "/intel/scaleio/*/numOfVolumes": {},
    "/intel/scaleio/*/totalReadBwc/*": {},
    "/intel/scaleio/*/totalWriteBwc/*": {}
},`

Environment : 
- Snap in docker container
- ScaleIO 1.32.5 clusters
- CentOS 7

I'll continue to analyze it.

Regards,
Red

**Comment by thomastaylor312** [comment]
@redsux Missed the alert on this. If you reenable the task, does it work again? I am wondering if the API had a small hiccup and returned an unexpected response. If it did, I'll try to figure out how to handle it.

**Comment by thomastaylor312** [comment]
@redsux Just following up on this. Have you seen more issues?

**Comment by redsux** [comment]
Sorry @thomastaylor312 I miss your answers !
Reenable the task works well.

As snap didn't match all our requirements we finally ends our tests. But I could restart my containers.

**Comment by thomastaylor312** [comment]
@redsux Are you ok with me closing this issue then? As for Snap meeting your requirements, we'd love to hear from you in the [Slack Channel](https://intelsdi-x.herokuapp.com/) about any feedback or pain points that you had so we can address/improve them if possible. Thanks for getting back!

**Comment by nanliu** [comment]
@redsux, I'm closing this issue. However please reach out if you have any feedbacks on how we can improve Snap to meet your needs.
